version: 2

sources:
  - name: snowflake_sources
    description: All the sources coming from Snowflake
    database: dbt_project
    schema: raw
    config:
      freshness:
        warn_after: {count: 900, period: day} 
        error_after: {count: 1200, period: day}
      loaded_at_query: |
        select convert_timezone('America/Los_Angeles', 'UTC', to_timestamp(max(_updated_micros))) from {{ this }}

    tables:
      - name: candidates
        description: Cadnidates list, staffing status, and their English level      
        config:
          freshness:
            warn_after: {count: 7, period: day} 
            error_after: {count: 30, period: day}
          loaded_at_query: |
            select convert_timezone('America/Los_Angeles', 'UTC', to_timestamp(max(_updated_micros))) from {{ this }}
      - name: employees
        description: Employees list, employment status, their skills, and job function
      - name: interviews
        description: List of interviews by candidates, interview status, and interviewers
        config:
          freshness:
            warn_after: {count: 365, period: day} 
            error_after: {count: 700, period: day}
          loaded_at_query: |
            select convert_timezone('America/Los_Angeles', 'UTC', to_timestamp(max(_updated_micros))) from {{ this }}
      - name: job_functions
        description: List of all the job functions
      - name: skills
        description: List of all the skills