repos:
  - repo: local
    hooks:
      - id: sqlfluff-lint
        name: sqlfluff lint
        entry: sqlfluff lint
        language: system
        files: \.sql$

      - id: sqlfluff-fix
        name: sqlfluff fix
        entry: sqlfluff fix
        language: system
        files: \.sql$